### ISSUE TITLE
Fixing yarpClean()

### ISSUE THREAD

**Issue by Nicogene** [robotology/yarpviz#7]
The function `yarpClean(...)` for now doesn't do anything, just a reminder for me.

**Comment by apaikan** [comment]
+1 @nicogene
Just a reminder: Yarpclean is obligatory! for now we do it from the command line before profiling yarp network. 

the reason is empty is that it needs some functions from yarp os impel which are not exported. 

if you plan to merge yarpviz into yarp repo then it is straight forward. otherwise you need to copy some code from yarp.

**Comment by Nicogene** [comment]
Hi @apaikan!
yes the idea is to put `yarpviz` inside `yarp`, in fact I think I will fix this issue once we complete this merge :smile:.
In `MainWindow.cpp` I added a `MessageBox`  for asking if the user want  to perform `yarp clean` before profiling because with the timeout set to 0.1 seconds there is the risk to kill  some port and process that are actually active for the latency of the wireless connections.
Saying "ok" the user assumes the responsibilities of this kind of risk. 
What do you think about it ?

**Comment by Nicogene** [comment]
Fixed by #8
